version: '2.3'
services:
  alfred:
    image: prompter
    runtime: nvidia
    volumes:
      - ../:/home/prompter
      - ~/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
    network_mode: "host"
    tty: true
